### ISSUE TITLE
Some questions！

### ISSUE THREAD

**Issue by wujiekd** [alibaba/easyrobust#1]
Hi, what are SIN and DebiasedCNN? Is there a link to the paper? Does the project implement these two methods? Looking forward to your reply, thanks.

**Comment by vtddggg** [comment]
Have added the paper link. See [here](https://github.com/alibaba/easyrobust#non-adversarially-robust-models)

We have implemented DebiasedCNN in easyrobust. To turn it on just set `--training_mode=debiased `
But for SIN you need to re-generate ImageNet train set based on AdaIN. You can refer to [this](https://github.com/rgeirhos/Stylized-ImageNet).

**Comment by vtddggg** [comment]
v0.2.0 has been released！
Now, you can clearly see the paper implementation of SIN and DebiasedCNN below.

SIN: https://github.com/alibaba/easyrobust/tree/main/examples/imageclassification/imagenet/SIN
DebiasedCNN: https://github.com/alibaba/easyrobust/tree/main/examples/imageclassification/imagenet/shape_texture_debiased_training

Thanks for your interests of our easyrobust!!
