### ISSUE TITLE
Problem of calculating regional gini index in easyrobust/examples/attacks/inequality/inequality_test.py line 110

### ISSUE THREAD

**Issue by Crazygay12138** [alibaba/easyrobust#13]
The shape of natural_gs_np is [c, w, h], because it's a pytorch input. However, you didn't transpose it to [w, h, c] before calling get_average_saliency_map(), which assumes input tensor should have shape [w, h, c]. This may result in higher regional gini value.

After changing it, calculated regional gini value should be lower than global ones, because the sum operator will makes the pixels within the region equal, which looks like bluring a image with a average filter(multiply whole image with a scalar won't change it's gini value).

**Comment by RjDuan** [comment]
Thank you very much for your interest in our work. We have reviewed the code and found that there is such an issue. 

We have made corrections in the code and we will update the results of Table 1 of the paper on the ICLR page. This correction does not affect the conclusions of the paper. 

Thank you again for your attention to our code, and please feel free to discuss any further questions if you have:)

**Comment by vtddggg** [comment]
We have updated the code in https://github.com/alibaba/easyrobust/commit/267c92a6916697fa41f73a0eacee99dfe64e9c61
