### ISSUE TITLE
question about visualization in BATS

### ISSUE THREAD

**Issue by yyyyyyyy0224** [alibaba/easyrobust#15]
Thanks for your great work
I don't know how to generate the visualization of Figure 1，can you share the code about it? Thanks!
![image](https://github.com/alibaba/easyrobust/assets/55536926/ca3d8379-74ed-42ef-99a6-ae8806cf9841)

**Comment by ZY123-GOOD** [comment]
Thanks for your interest.
**First**, import matplotlib.pyplot as plt
**Then**, calculate the score of in-distribution samples as Score_ID and calculate the score of out-of-distribution samples as Score_OOD.
**At last**, plot the histogram as:

`n1, bins1, patches1  = plt.hist(Score_ID,bins=100,density=True,color='orange',alpha=0.)
plt.fill_between(bins1[:-1], n1, color='orange', alpha=1.0,label="ID")
plt.plot(bins1[:-1],n1,'--',color='coral')
`
`
n2, bins2, patches2  = plt.hist(Score_OOD,bins=100,density=True,color='lightgreen',alpha=0.)
plt.fill_between(bins2[:-1], n2, color='lightgreen', alpha=0.8,label="OOD")
plt.plot(bins2[:-1],n2,'--',color='green')
`

**Comment by zqyjww** [comment]
How do I calculate Score_ID and Score_OOD? May I ask if you can provide a complete visualization code? thank you!!

**Comment by ZY123-GOOD** [comment]
Firstly, the ID (In-Distribution) and OOD (Out-of-Distribution) scores are calculated for each sample using the method at your disposal. For example, you can choose Energy Score. Once you have the scores, you can plot histograms to visualize the distributions of the scores. This will help you understand the differences between the ID and OOD samples and evaluate the effectiveness of your model in detecting OOD instances. 
I believe you can handle this simple plotting task. You can refer to this tutorial to draw histograms. 
https://www.runoob.com/matplotlib/matplotlib-hist.html
For how to calculate overlap, you can check issue #18.

**Comment by zqyjww** [comment]
Okay, thank you. May I ask if I have two sets of images, one is the original image and the other is the image generated by adversarial attacks? I will use the vit model to calculate ScoreID and ScoreOOD, and the resnet18 model to calculate ScoreID and ScoreOOD. Will using different models to measure affect the final distribution detection results?

**Comment by ZY123-GOOD** [comment]
Based on my experience, using different models for measurement does indeed affect the final distribution detection results. For example, if you generate adversarial samples using ViT and then compute the OOD scores for these adversarial samples and the ID scores for clean samples using ViT, the results will naturally differ from those obtained from the perspective of a ResNet model.

**Comment by zqyjww** [comment]
Okay, thank you. How can I obtain the pt files of features_mean and features_std for resnet18 and resnet50?

**Comment by ZY123-GOOD** [comment]
You can check the issue https://github.com/alibaba/easyrobust/issues/9
If you have any more questions, please feel free to contact me.
