### ISSUE TITLE
Questions on reproducing BATS

### ISSUE THREAD

**Issue by fanghenshaometeor** [alibaba/easyrobust#17]
Could you please provide the `features_mean` and `features_std` for ResNet50 and MobileNet on ImageNet? I fail to reproduce the reported ood results in your paper.

I follow the code piece in #9 to generate `features_mean` and `features_std` on the features right before the linear layer and set `lamb=1.25` for ResNet50 following the Appendix E.2.2 in the paper, but only to attain terrible performance. Did I still miss something?

Looking forward to your reply

**Comment by ZY123-GOOD** [comment]
Thanks for your good question. You can use the weights of the last batch normalization (BN) layer for RN50 and MobileNet as features_std, and the biases as features_mean. Please note that it should be the BN's weight and bias, not the running_mean and running_var. If you have followed these steps and still encounter suboptimal performance, there's no need to worry. You can experiment with your reproduced results for comparison. In our further research, we've discovered that the model's structure and parameters significantly impact experimental results. This insight is elaborated in the paper titled "Rethinking Out-of-Distribution Detection From a Human-Centric Perspective" (https://arxiv.org/abs/2211.16778). Existing algorithms face challenges in ensuring superiority across different models. Perhaps variations in our model parameters have contributed to divergent performance. Future research in OOD detection may focus on exploring algorithms that are insensitive to the model choice.
If you have any further questions, please feel free to email me at ee_zhuy@zju.edu.cn or chat with me on WeChat.
