### ISSUE TITLE
Question about BATS

### ISSUE THREAD

**Issue by GewelsJI** [alibaba/easyrobust#9]
Hi, @vtddggg 

Thank you for providing such a nice project.

I do not know how to generate two *.pt files ([vit_features_mean.pt](https://github.com/alibaba/easyrobust/blob/main/examples/ood_detection/BATS/vit_features_mean.pt) & [vit_features_std.pt](https://github.com/alibaba/easyrobust/blob/main/examples/ood_detection/BATS/vit_features_std.pt) ). Could you provide the code for this?

Best.

**Comment by ZY123-GOOD** [comment]
Thanks for your interest. We randomly choose some samples and count the mean and standard deviation of their features on each channel. We provide an example as follows.

We are glad you are interested in our paper. This work mainly follows settings in some existing work. However, it is worth noting that in further research and thought, we found that **the current setting of the OOD detection task may need to be reconsidered**.
We share our new findings in the paper : _Rethinking Out-of-Distribution Detection From a Human-Centric Perspective_ ( https://arxiv.org/abs/2211.16778 ). We find that the simple baseline OOD detection method (MSP) can achieve comparable and even better performance than the recently proposed methods, which means that the development in OOD detection in the past years may be overestimated.

I hope my answer can help you. If you have any other questions, please don't hesitate to email me at ee_zhuy@zju.edu.cn.

```
#We choose 1500 samples.
list_id = torch.zeros((768,1500))
for batch_idx, (inputs, true_class) in enumerate(data_loader):
    model.eval()

    #Choose 1500 samples.
    if batch_idx==1500:
        break 
    inputs = inputs.cuda()
    
    #Get the features (768 channels).
    features = model.backbone(inputs)[0][-1]
    current_outputs = features.reshape(features.shape[0],-1).detach()

    for j in range(current_outputs.shape[0]):
        for k in range(768):
            list_id[k][batch_idx] = current_outputs[j][k] 
            
features_mean=torch.zeros(768)
features_std=torch.zeros(768)
for i in range(768):
    features_mean[i]=list_id[i].mean()
    features_std[i]=list_id[i].std()        
    
torch.save(features_mean,"vit_features_mean.pt")
torch.save(features_std,"vit_features_std.pt")
```

**Comment by GewelsJI** [comment]
Nice answer. Hope you are doing well.
